### ISSUE TITLE
DB 이전을 위해서 사용하는경우, 전체 Project를 한번에 export 지원 문의

### ISSUE THREAD

**Issue by Jinwoo0503** [yona-projects/yona-export#23]
H2 DB에서 마리아DB로 전환하려고 합니다

Yona v1.12.0 를 사용중이며, 다음과 같이 진행할 계획을 준비중입니다
- 우선 동일한 Yona 버전의 마리아 DB 버전을 준비하고
- H2 DB에 있는 데이터를 yona-exprot로 전체 backup
- backup된 데이터를 마리아 DB를 사용하는 yona에 업로드
- 마리아 DB를 사용하는 Yona의 버전을 업그레이드

위와 같은 순서로 진행하려고 합니다

yona-export의 README를 살펴봤을 때
Yona Project 전체를 Export하는 부분에 대한 안내가 없는 것 같습니다

이 작업을 수행할 수 있는 방법이 있나요?

---
To: @doortts @hurcy

**Comment by doortts** [comment]
이전해야 하는 프로젝트가 몇 개 정도 되세요?

**Comment by Jinwoo0503** [comment]
@doortts 답변 감사드립니다
대략 100개를 넘어설 것 같습니다(유저의 개인 프로젝트 포함)

사내의 메인 Yona라서, 양이 좀.. 많습니다
그룹도 다수 있는 상태입니다

---
Yona를 잘 사용중입니다
꾸준한 개발 및 업데이트에 감사드립니다 :)

덕분에 잘 쓰고 있습니다
이번에 업데이트 하고 계속 사용할 예정이라
번거로우시겠지만 지원 부탁드립니다(꾸벅)

**Comment by doortts** [comment]
이런경우 DB to DB 로 이전하는것이 유리할것으로 생각됩니다만, H2 에서 MariaDB(MySQL)로 DB 이전은 진행되어본적은 없습니다.
따라서 프로젝트 목록을 만들어서 bulk.sh 파일처럼 배치실행을 하시는 방법이 좋을 것으로 생각됩니다.

우선 한 두개 프로젝트를 yona-export 로 export/import 잘 되는지 먼저 테스트 해보시면 좋을 것 같아요.

**Comment by Jinwoo0503** [comment]
@doortts 답변 감사드립니다 테스트해보도록 하겠습니다
혹시, DB to DB로 이전할 때 참고할 수 있는 자료 등을 얻을 수 있을까요?

DB to DB로 이전하는 것을 선호합니다
그렇지만, 다른 종류로 변경하는 것을 진행해본적이 없어서 문의 드립니다

DB to DB 이전을 위해 테스트해볼 수 있는 자료가 있다면 공유부탁드립니다 (스크립트, python 코드 등)

---
또는, 프로젝트 전체의 list를 읽기 위해 제공되는 api 등이 있다면 공유 부탁드립니다 :)

**Comment by doortts** [comment]
https://github.com/yona-projects/yona/blob/yona-h2/conn.sh 스크립트 혹은 이 스크립트를 기반으로 경로 수정등을 하시면 h2 db 파일에 직접  command line 으로 접근 가능하실겁니다. 그 이후에 project 테이블을 조회하시면 owner 와 projectName 값의 목록을 발췌가능하실겁니다.

DB schema 참고: https://github.com/yona-projects/yona/blob/next/conf/evolutions/default/1.sql#L260

**Comment by Jinwoo0503** [comment]
@doortts 답변감사합니다

- 우선 yona-export를 테스트 해보고자 readme를 통해 npm install 및 npm export를 진행했습니다
    -  npm export를 진행하는 동안 다음과 같은 문제가 발생합니다
    ```shell
  import unirest from 'unirest';
         ^^^^^^^
  
  SyntaxError: Unexpected identifier
      at Module._compile (internal/modules/cjs/loader.js:723:23)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
      at startup (internal/bootstrap/node.js:283:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! yona-export@0.5.0 start: `node app/app.js "export"`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the yona-export@0.5.0 start script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    ```
   - 추가로 다음 log를 공유드립니다
   ```shell
  { 'yona-export': '0.5.0',
    npm: '6.14.4',
    ares: '1.15.0',
    brotli: '1.0.7',
    cldr: '36.1',
    http_parser: '2.9.3',
    icu: '66.1',
    modules: '64',
    napi: '5',
    nghttp2: '1.40.0',
    node: '10.19.0',
    openssl: '1.1.1d',
    tz: '2022a',
    unicode: '13.0',
    uv: '1.34.2',
    v8: '6.8.275.32-node.55',
    zlib: '1.2.11' }
   ```

**Comment by Jinwoo0503** [comment]
@doortts 위 Nodejs 문제는 해결되었습니다
nodejs의 버전 문제 였습니다 더 상위 버전을 설치하니 해결되었습니다 :)

몇 가지 더 문의드릴게 있어서 댓글을 추가합니다
- Yona Group 및 Project이름에 한글이 포함된 경우에도 잘 작동하나요?
    - 만약 작동하지 않는다면, 해결할 수 있는 방법이 있나요?

- export된 것을 import 시에 User는 어떻게 되나요?
    - 자동으로 추가되나요? 아니면 새로 가입을 해야하나요?
        - 새로 가입해야하는 경우라면, db의 특정 테이블을 복사하는 걸로 해결될 수 있나요?

**Comment by Jinwoo0503** [comment]
DB to DB 로 변환하여 해결했습니다 :)

**Comment by doortts** [comment]
제가 이슈를 놓치고 있었네요. DB to DB 이전 쉽지 않았을텐데 고생하셨습니다!
혹시 어떤식으로 하셨는지 남겨주시면 다른 분들에게도 도움이 되지 않을까 싶습니다만 부탁드리기 부끄럽네요.
